apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-service.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "project-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "project-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.deployment.annotations | nindent 8 }}
      labels:
        {{- include "project-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "project-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.deployment.securityContext.runAsUser }}
            runAsGroup: {{ .Values.deployment.securityContext.runAsGroup }}
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.ports.http }}
          envFrom:
            - secretRef:
                name: {{ .Values.sealedSecret.name }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}

