apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL:https://github.com/soodNivesh/docker-node-example.git
    targetRevision: main
    path: kubernetes/dev/auth-service/helm

  destination:
    server: https://kubernetes.default.svc
    namespace: auth-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - ApplyOutOfSyncOnly=true

