apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-service-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/possibl-ai/lightspeed-iac.git
    targetRevision: main
    path: kubernetes/dev/project-service/helm

  destination:
    server: https://kubernetes.default.svc
    namespace: project-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - ApplyOutOfSyncOnly=true
