apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: backend
  labels:
    app: backend
type: Opaque
data:
  db_name: ZGF0YWJhc2Ux
  db_user: ZGItdXNlcg==
  db_password: dmFsdWVAMTIz
