apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-gateway-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:possibl-ai/lightspeed-iac.git
    targetRevision: main
    path: kubernetes/dev/external-gateway-service

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
