{{- if .Values.sealedSecret.create }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "{{ .Values.sealedSecret.clusterWide }}"
  name: {{ .Values.sealedSecret.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "{{ .Values.sealedSecret.clusterWide }}"
      name: {{ .Values.sealedSecret.name }}
      namespace: {{ .Values.namespace.name }}
{{- end }}

