apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.name" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "auth-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
    - name: grpc
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: {{ .Values.service.ports.grpc.targetPort }}

