apiVersion: monitoring.googleapis.com/v1
kind: AlertPolicy
metadata:
  name: backend-high-cpu
spec:
  combiner: OR
  conditions:
  - displayName: High CPU
    conditionThreshold:
      filter: metric.type="kubernetes.io/container/cpu/core_usage_time"
      comparison: COMPARISON_GT
      thresholdValue: 0.8
      duration: 300s

