apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-sa
  namespace: auth-dev
  annotations:
    # Replace with your GCP service account to enable Workload Identity
    # iam.gke.io/gcp-service-account: "<GSA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com"
    iam.gke.io/gcp-service-account: "github-service-account@rapidqs-lightspeed.iam.gserviceaccount.com"
