apiVersion: v1
kind: Namespace
metadata:
  name: project-dev
  labels:
    app.kubernetes.io/name: project-service
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: project-dev
  metadata:
  labels:
    app: project-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      annotations:
        cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
      labels:
        app: project-service
    spec:
      # Use the Kubernetes ServiceAccount annotated for Workload Identity
      serviceAccountName: gke-sa
      containers:
        - name: project-service
          # Image name will be overridden via kustomization.yaml (images:)
          # Logical image reference (kustomize will replace newName)
          image: project-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
            #- containerPort: 50051
            #  name: grpc
          # Consume DB credentials and Firebase JSON from a single Kubernetes Secret
          # The SealedSecret controller will create a Kubernetes Secret named `project-service-secrets` from the SealedSecret.
          envFrom:
            - secretRef:
               name: project-service-secrets
          readinessProbe:
            httpGet:
              path: /project/health
              port: 3001
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /project/health
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          # Mount the Firebase service account JSON from the same Secret (key: firebase-service-account.json)
          #env:
          #  - name: FIREBASE_SERVICE_ACCOUNT_PATH
          #    value: /secrets/firebase-service-account.json
          #volumeMounts:
          #  - name: sealed-secrets-volume
          #    mountPath: /secrets/firebase-service-account.json
          #    subPath: firebase-service-account.json
          #    readOnly: true
      #volumes:
      #  - name: sealed-secrets-volume
      #    secret:
      #      secretName: sealed-secrets
      #      optional: false

---

apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: project-dev
  labels:
    app: project-service
  #annotations:
  #  cloud.google.com/backend-config: '{"default":"auth-config"}'
  #  cloud.google.com/app-protocols: '{"http":"HTTP"}'
spec:
  type: ClusterIP
  selector:
    app: project-service
  ports:
    - name: http
      port: 80
      targetPort: 3001
    #- name: grpc
    #  port: 50051
    #  targetPort: 50051