apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace applied by these resources
namespace: backend

resources:
- deployment.yaml
- service-account.yaml
- sealed-secrets.yaml

# Replace the image used by the Deployment. Edit these values for your project/registry.
    # Set newName to your registry path (Artifact Registry or GCR)
    # Example (GCR): gcr.io/my-project/auth-service
    # Example (Artifact Registry): us-central1-docker.pkg.dev/my-project/my-repo/auth-service
    # Include the tag directly in newName to set both path and tag here
images:
- name: backend 
  newName: asia-south2-docker.pkg.dev/corded-forge-481305-n1/ci-repo/backend:${{ github.sha }}

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize

