apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-sa
  namespace: backend
  annotations:
    # Replace with your GCP service account to enable Workload Identity
    # iam.gke.io/gcp-service-account: "<GSA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com"
    iam.gke.io/gcp-service-account: "github-work-service-account@corded-forge-481305-n1.iam.gserviceaccount.com"
