apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-httproute-to-auth-service
  namespace: auth-dev
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: auth-dev   # from the namespace where the Gateway lives or where HTTPRoutes originate
  to:
    - group: ""
      kind: Service
      name: auth-service      # optional: can omit name to allow any service in auth-dev