apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth-route
  namespace: auth-dev
spec:
  parentRefs:
    - name: external-api-gateway
      namespace: ingress-dev
  hostnames:
    - api.lightspeed.rapidqs.com   # optional; must match the Gateway hostname if present
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: auth-service
          namespace: auth-dev
          port: 80
