apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerCertificate
metadata:
  name: lightspeed-api-cert
  namespace: ingress-dev
spec:
  description: "TLS certificate for api.lightspeed.rapidqs.com (DNS Auth)"
  sanDnsNames:
    - api.lightspeed.rapidqs.com
  dnsAuthorizations:
    - name: lightspeed-dns-auth
  issuanceConfig:
    lifetime: 31536000s
    rotationWindowPercentage: 33
