apiVersion: v1
kind: Namespace
metadata:
  name: ingress-dev
  
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-api-gateway
  namespace: ingress-dev
  annotations:
    # instruct GKE to provision the managed cert
    networking.gke.io/managed-certificates: lightspeed-api-cert
spec:
  gatewayClassName: gke-l7-regional-external-managed
  #gatewayClassName: gke-l7-rilb
  #addresses:
   # - type: NamedAddress
    #  value: internal-dev-gateway-ip
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: api.lightspeed.rapidqs.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: lightspeed-api-cert
            kind: CertificateManagerCertificate
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      hostname: api.lightspeed.rapidqs.com
     # optional internal hostname; can be omitted
      allowedRoutes:
        namespaces:
          from: All
    # the reserved internal IP (optional). Remove this block to let GKE choose IP.
