apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-http-to-https
  namespace: ingress-dev
spec:
  parentRefs:
    - name: external-api-gateway
      namespace: ingress-dev
      sectionName: http

  hostnames:
    - api.lightspeed.rapidqs.com

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
